#define IDC_TOP_MARGIN        768
#define IDC_BOT_MARGIN        769
#define IDC_LEFT_MARGIN       766
#define IDC_RIGHT_MARGIN      767
#define IDC_PRINT_JUSTIFIED   772
#define IDC_RANGE_ALL         773
#define IDC_RANGE_SELECTED    774
#define IDC_REPLACE_BLOCK     759
#define IDC_REPLACE_FILE      758
#define IDC_REPLACE_STRING    755
#define IDC_REPLACE_VERIFY    757
#define IDC_REPLACE_WITH      756
#define IDC_FILE              763
#define IDC_SEARCH_BACK       754
#define IDC_SEARCH_BEGIN      752
#define IDC_SEARCH_CASE       751
#define IDC_SEARCH_FOR        753
#define IDC_SEARCH_STRING     750
#define IDC_UNDO_COL          761
#define IDC_UNDO_LINE         760
#define IDC_UNDO_TEXT         762
#define IDC_UNDO_HEADER       777
#define IDC_JUMP_TO           778
#define IDC_FONT_TYPES        779
#define IDC_FONT_POINTS       780
#define IDC_LIST_BOX          781

#define IDC_CTL_VISIBLE       800
#define IDC_CTL_DISABLED      801
#define IDC_CTL_GROUP         802
#define IDC_CTL_TABSTOP       803
#define IDC_CTL_BORDER        804
#define IDC_CTL_WORD_WRAP     805
#define IDC_CTL_PRINT_VIEW    806
#define IDC_CTL_HSCROLL       807
#define IDC_CTL_VSCROLL       808
#define IDC_CTL_SHOW_STATUS   809
#define IDC_CTL_SHOW_RULER    810
#define IDC_CTL_BORDER_MARGIN 811
#define IDC_CTL_OUTPUT_RTF    812
#define IDC_CTL_READ_ONLY     813
#define IDC_CTL_PAGE_MODE     814
#define IDC_CTL_SHOW_TOOLBAR  815
#define IDC_CTL_FITTED_VIEW   816

#define IDC_SEC_COLUMNS       830
#define IDC_SEC_COL_SPACE     831
#define IDC_SEC_NEW_PAGE      832

#define IDC_BAR_BOLD          840
#define IDC_BAR_ITALIC        841
#define IDC_BAR_ULINE         842

#define IDC_BAR_JUST_LEFT      843
#define IDC_BAR_JUST_RIGHT     844
#define IDC_BAR_JUST_CENTER    845
#define IDC_BAR_DOUBLE_SPACE   846
#define IDC_BAR_INDENT_LEFT    847
#define IDC_BAR_INDENT_RIGHT   848
#define IDC_BAR_INDENT_HANGING 849
#define IDC_BAR_PARA_STYLE     850
#define IDC_BAR_JUST_BOTH      851

#define IDC_PICT_WIDTH         860
#define IDC_PICT_HEIGHT        861
#define IDC_PICT_ALIGN_BOT     862
#define IDC_PICT_ALIGN_MIDDLE  863
#define IDC_PICT_ALIGN_TOP     864

#define IDC_SHADING            874
#define IDC_BOX_TOP            875
#define IDC_BOX_BOT            876
#define IDC_BOX_LEFT           877
#define IDC_BOX_RIGHT          878
#define IDC_BOX_DOUBLE         879
#define IDC_BOX_THICK          880

#define IDC_PASTE              881
#define IDC_PASTE_LINK         882
#define IDC_PASTE_SOURCE       883
#define IDC_PASTE_ITEM         884

#define IDC_TABLE_ROWS         885
#define IDC_TABLE_COLS         886
#define IDC_TABLE_SEL_COLS     887
#define IDC_TABLE_SEL_ROWS     888
#define IDC_TABLE_SEL_CELLS    889
#define IDC_TABLE_CUR_ROW      890
#define IDC_TABLE_ALL_ROWS     891

#define IDC_JUST_LEFT          892
#define IDC_JUST_CENTER        893
#define IDC_JUST_RIGHT         894

#define IDC_CELL_SHADE         895

#define IDC_PV_ZOOM            896
#define IDC_PV_PAGES           897
#define IDC_PV_CLOSE           898
#define IDC_PV_PAGE_NO         899

#define IDC_PARA_SPACE_BEF     900
#define IDC_PARA_SPACE_AFT     901
#define IDC_PARA_SPACE_BET     902

#define IDC_PAGE_NO            903

#define IDC_FNOTE_CHAR         904
#define IDC_FNOTE_TEXT         905
#define IDC_FNOTE_SUPSCR       906

#define IDC_PV_PRINT           907

#define IDC_TEXT_BOX           908
#define IDC_RECT               909
#define IDC_LINE               910

#define IDC_SS_CHAR            911
#define IDC_SS_PARA            912
#define IDC_SS_NEW             913
#define IDC_SS_NAME            914
#define IDC_SS_NAME_LABEL      915
#define IDC_SS_BOX_LABEL       916

#define IDC_PERCENT            917

#define IDC_TAB_TYPE_LEFT      918
#define IDC_TAB_TYPE_RIGHT     919
#define IDC_TAB_TYPE_CENTER    920
#define IDC_TAB_TYPE_DECIMAL   921
#define IDC_TAB_DOT            922
#define IDC_TAB_HYPH           923
#define IDC_TAB_ULINE          924
#define IDC_TAB_POS            925
#define IDC_TAB_NONE           926

#define IDC_PORTRAIT           927
#define IDC_LANDSCAPE          928
#define IDC_HEIGHT             929

#define IDC_VERT_PAGE          930
#define IDC_VERT_MARG          931
#define IDC_VERT_PARA          932
#define IDC_HORZ_MARG          933
#define IDC_HORZ_PAGE          934

#define IDC_LINE_THICK         935
#define IDC_LINE_COLOR         936
#define IDC_LINE_SOLID         937
#define IDC_LINE_DOTTED        938
#define IDC_FILL_XPARENT       939
#define IDC_FILL_COLOR         940
#define IDC_LINE_DRAW          941

#define IDC_TABLE_ALL          942
#define IDC_EXACT              943
#define IDC_UNITS              944
#define IDC_AUTO               945
#define IDC_MIN                946
#define IDC_HEIGHT_LABEL       947
#define IDC_RESTART_PAGE_NO    948
#define IDC_BEST_FIT           949
#define IDC_FIX_WIDTH          950
#define IDC_FIX_WIDTH_PCT      951
#define IDC_COLOR              952

#define IDC_FIRST_PAGE         953
#define IDC_LAST_PAGE          954
#define IDC_RANGE_PAGES        955
#define IDC_ALIGN_TOP          956
#define IDC_ALIGN_CTR          957
#define IDC_ALIGN_BOT          958
#define IDC_CUR_PAGE           959

#define IDC_HDR_MARGIN         960
#define IDC_FTR_MARGIN         961
#define IDC_ALL_SECTS          962
#define IDC_ZORDER             963
#define IDC_MARGIN             964

#define IDC_INSERT             965
#define IDC_DELETE             966
#define IDC_GOTO               967
#define IDC_COPIES             968
#define IDC_COLATE             969
#define IDC_EXPAND             970
#define IDC_REDUCE             971
#define IDC_RESET              972
#define IDC_ADJ                973
#define IDC_ADJ_TITLE          974

#define IDC_FIRST_BIN          975
#define IDC_NEXT_BIN           976
#define IDC_FIELD_NAME         977
#define IDC_FIELD_DATA         978
#define IDC_MAX_LEN            979
#define IDC_BORDER             980
#define IDC_FONT               981
#define IDC_BOXSIZE            982
#define IDC_CHECKED            983
#define IDC_STYLE_BOX          984

#define IDC_PARA_SPACE         985
#define IDC_PARA_SPACE_LBL     986

#define IDC_PICT_SIZE_LBL      987


#define IDC_NAME               988
#define IDC_NESTED             989
#define IDC_RESTART_AT_SEC     990
#define IDC_OVERRIDE           991
#define IDC_LIST_ITEM          992
#define IDC_LIST_OR            993
#define IDC_LIST_OR_BOX        994
#define IDC_LEVEL              995
#define IDC_START_AT           996
#define IDC_NUM_TYPE           997
#define IDC_CHAR_AFT           998
#define IDC_FONTS              999
#define IDC_TEXT              1000
#define IDC_RESTART           1001
#define IDC_LEGAL             1002
#define IDC_REFORMAT          1003
#define IDC_NO_RESET          1004
#define IDC_COLOR_TOP         1005
#define IDC_COLOR_BOT         1006
#define IDC_COLOR_LEFT        1007
#define IDC_COLOR_RIGHT       1008
#define IDC_COLOR_ALL         1009
#define IDC_ALIGN_BASE        1010
#define IDC_OFFSET            1011
#define IDC_OFFSET_VAL        1012
#define IDC_WIDTH             1013

#define IDC_HORZ              1014
#define IDC_TOP_TO_BOT        1015
#define IDC_BOT_TO_TOP        1016
#define IDC_DEF               1017
#define IDC_RTL               1018
#define IDC_LTR               1019
#define IDC_LBL_LEFT          1020
#define IDC_LBL_RIGHT         1021
#define IDC_BOX_BETWEEN       1022
#define IDC_LINK_TEXT         1023
#define IDC_LINK_CODE         1024

#define IDC_WRAP_THRU         1025
#define IDC_NO_WRAP           1026
#define IDC_WRAP_AROUND       1027

#define IDC_PAPER             1028
#define IDC_PAPER_WIDTH       1029
#define IDC_PAPER_HEIGHT      1030
#define IDC_PAPER_WIDTH_LABEL 1031
#define IDC_PAPER_HEIGHT_LABEL 1032

#define IDC_BIN               1033
#define IDC_COPY              1034
#define IDC_BIN_LBL           1035
#define IDC_COPY_LBL          1037
#define IDC_PAGE_REF          1038
#define IDC_OUTLINE           1039
